# Generated by Django 2.2 on 2021-08-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data2display', '0002_auto_20210812_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapost',
            name='author',
        ),
    ]
