# Generated by Django 2.2 on 2021-08-13 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data2display', '0004_auto_20210812_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapost',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
