# Generated by Django 2.2 on 2021-08-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data2display', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapost',
            options={'ordering': ('-updated',)},
        ),
        migrations.RenameField(
            model_name='datapost',
            old_name='uploaded',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='datapost',
            name='title',
        ),
        migrations.AddField(
            model_name='datapost',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datapost',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='datapost',
            name='weight',
            field=models.FloatField(),
        ),
    ]
